# NumPy

# NumPy Operations

NumPy is a powerful library for numerical operations in Python. Here are some basic examples:

If you are using it in your local PC then install it through the terminal. Else, skip this step.

This cell installs the `numpy` library using pip. It's skipped if numpy is already installed.

In [ ]:
pip install numpy

This cell imports the numpy library and creates a 1D NumPy array from a Python list.

In [5]:
import numpy as np
# From Python list
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

Original array: [1 2 3 4 5]


### Exercise 1: Array Creation and Basic Element-wise Operations

Create a NumPy array from a Python list. Then, perform element-wise addition and multiplication on this array.

In [6]:
import numpy as np

# Create a NumPy array from a Python list
arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)

# Add 5 to each element
print("Array after adding 5:", arr + 5)

# Multiply each element by 2
print("Array after multiplying by 2:", arr * 2)

Original Array: [10 20 30 40 50]
Array after adding 5: [15 25 35 45 55]
Array after multiplying by 2: [ 20  40  60  80 100]


### Exercise 2: Creating Special Arrays

Create a 2x3 array of zeros, a 3x2 array of ones, and a 2x2 array of random floating-point numbers between 0 and 1.

In [ ]:
# Create a 2x3 array of zeros
zeros_array = np.zeros((2, 3))
print("2x3 Zeros Array:\n", zeros_array)

# Create a 3x2 array of ones
ones_array = np.ones((3, 2))
print("\n3x2 Ones Array:\n", ones_array)

# Create a 2x2 array of random numbers
random_array = np.random.rand(2, 2)
print("\n2x2 Random Array:\n", random_array)

2x3 Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]

3x2 Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

2x2 Random Array:
 [[0.78396321 0.17060484]
 [0.76059608 0.02456626]]


### Exercise 3: Array Attributes

Create a 2D NumPy array and print its shape, size, and number of dimensions.

This cell demonstrates how to create 2D and 3D NumPy arrays and then prints their shape, size, and number of dimensions.

In [7]:
# Create a 2D array
import numpy as np
array_2d = np.array([[1, 2], [3,4]])
print("2D Array:\n", array_2d)

# Print its shape
print("Shape of the array:", array_2d.shape)

# Print its size (total number of elements)
print("Size of the array:", array_2d.size)

# Print its number of dimensions
print("Number of dimensions:", array_2d.ndim)

# Create a 3D array
array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

print("3D Array:\n", array_3d)


2D Array:
 [[1 2]
 [3 4]]
Shape of the array: (2, 2)
Size of the array: 4
Number of dimensions: 2
3D Array:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### Exercise 4: Reshaping an Array

Create a 1D array with numbers from 1 to 9 (inclusive) and then reshape it into a 3x3 2D array.

In [9]:
# Create a 1D array
arr_1d = np.arange(1, 10)
print("Original 1D Array:", arr_1d)
print(arr_1d.shape)

# Reshape it into a 3x3 2D array
reshaped_array = arr_1d.reshape(3, 3)
print("\nReshaped 3x3 Array:\n", reshaped_array)

Original 1D Array: [1 2 3 4 5 6 7 8 9]
(9,)

Reshaped 3x3 Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Exercise 5: Conditional Selection

Create a NumPy array and select all elements that are greater than 15.

In [ ]:
# Create an array
exercise_arr = np.array([10, 15, 20, 25, 30, 5, 35])
print("Original Array:", exercise_arr)
arraged_arr = np.sort(exercise_arr)
print("Sorted Array:", arraged_arr)
# Select elements greater than 15
selected_elements = exercise_arr[exercise_arr > 15]
print("Elements greater than 15:", selected_elements)

Original Array: [10 15 20 25 30  5 35]
Sorted Array: [ 5 10 15 20 25 30 35]
Elements greater than 15: [20 25 30 35]


### Exercise 6: Mathematical and Aggregation Functions

Create a NumPy array and calculate its square root, sine, sum, maximum, minimum, and standard deviation.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # [5 7 9]
print(a * b)   # [ 4 10 18]
print(a ** 2)  # [1 4 9]

[5 7 9]
[ 4 10 18]
[1 4 9]


In [3]:
# Create an array
math_arr = np.array([1, 4, 9, 16, 25])
print("Original Array:", math_arr)

# Calculate square root
print("Square root:", np.sqrt(math_arr))

# Calculate sine
print("Sine:", np.sin(math_arr))

# Calculate sum
print("Sum:", np.sum(math_arr))

# Calculate maximum
print("Maximum:", np.max(math_arr))

# Calculate minimum
print("Minimum:", np.min(math_arr))

# Calculate standard deviation
print("Standard Deviation:", np.std(math_arr))

Original Array: [ 1  4  9 16 25]
Square root: [1. 2. 3. 4. 5.]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Sum: 55
Maximum: 25
Minimum: 1
Standard Deviation: 8.648699324175862


### Exercise 7: Matrix Multiplication and Transpose

Create two 2x2 NumPy arrays. Perform matrix multiplication between them and find the transpose of one of the arrays.

In [ ]:
# Create two 2x2 arrays
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", matrix_a)
print("\nMatrix B:\n", matrix_b)

# Perform matrix multiplication
matrix_product = np.dot(matrix_a, matrix_b)
print("\n Matrix Product (A x B):\n", matrix_product)

# Find the transpose of Matrix A
matrix_a_transpose = matrix_a.T
print("\nTranspose of Matrix A:\n", matrix_a_transpose)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

 Matrix Product (A x B):
 [[19 22]
 [43 50]]

Transpose of Matrix A:
 [[1 3]
 [2 4]]


### Exercise 8: measures of central tendency

This cell uses the `statistics` module to calculate measures of central tendency (mean, median, mode, multimode) and dispersion (variance, standard deviation) for a sample dataset.

In [ ]:
import statistics
# Sample dataset
data = [12, 15, 12, 18, 20, 15, 12, 22, 15]

# Measure the central tendency
mean_value = statistics.mean(data)
median_value = statistics.median(data)
mode_value = statistics.mode(data)
multimode_values = statistics.multimode(data)

# Measure the dispersion
variance_value = statistics.variance(data)
std_value = statistics.stdev(data)

print(f"Dataset: {data}")
print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Mode (1st mode): {mode_value}")
print(f"All Modes: {multimode_values}")
print(f"Variance: {variance_value}")
print(f"Standard Deviation: {std_value}")

Dataset: [12, 15, 12, 18, 20, 15, 12, 22, 15]
Mean: 15.666666666666666
Median: 15
Mode (1st mode): 12
All Modes: [12, 15]
Variance: 13.25
Standard Deviation: 3.640054944640259
